#!/usr/bin/env bash
# Build the single static stampd binary (HTTP server + CLI in one).
set -e
cd "$(dirname "$0")"
MACHIN="${MACHIN:-machin}"

# Embed web/index.html into an MFL function landing_html() (JSON string escaping == MFL
# string escaping), so the hosted calculator ships inside the binary — no asset files.
python3 - <<'PY'
import json
html = open("web/index.html").read()
with open("src/assets.src", "w") as f:
    f.write("// AUTO-GENERATED by build.sh from web/index.html — do not edit by hand.\n")
    f.write("func landing_html() (s) { s = " + json.dumps(html, ensure_ascii=False) + " }\n")
print("embedded web/index.html -> src/assets.src")
PY

mkdir -p build
"$MACHIN" encode \
  framework/machweb.src \
  src/sdlt.src src/core.src src/cli.src src/assets.src src/server.src \
  > build/stampd.mfl
"$MACHIN" build build/stampd.mfl -o stampd
echo "built ./stampd"
